version: 0.0
os: linux
files:
  - source: /dist/itmstl
    destination: /var/www/html

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: bin/app-before
      timeout: 30
      runas: root
  ApplicationStop:
    - location: bin/app-stop
      timeout: 30
      runas: root
  AfterInstall:
    - location: bin/app-after
      timeout: 30
      runas: root
  ApplicationStart:
    - location: bin/app-start
      timeout: 120
      runas: root
  ValidateService:
    - location: bin/app-validate
      timeout: 30
      runas: root